name: Deploy Pages

on:
  push:
    branches: [ "main" ]   # kör på main i det här miljö-repot
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Om sajten ligger i repo-roten, ladda upp allt.
      # Har du en 'site' eller 'dist'-mapp, sätt path: dit.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'   # byt till 'dist' om du har build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
